apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: app-claim
  name: app-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: first-sc
