apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: celery-claim
  name: celery-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: first-sc
